# Generated by Django 2.2.10 on 2020-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='imie',
            field=models.CharField(default='ania', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='nazwisko',
            field=models.CharField(default='koziera', max_length=100),
            preserve_default=False,
        ),
    ]
