# Generated by Django 2.2.10 on 2020-04-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0002_auto_20200402_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
