# Generated by Django 2.2.10 on 2020-04-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wymiana', '0002_wymiana_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wymiana',
            name='zdjecie',
            field=models.ImageField(default='produkt.png', upload_to='wymiany/'),
        ),
    ]
