# Generated by Django 2.2.10 on 2020-04-04 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wymiana', '0003_auto_20200404_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='WymianaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='files')),
                ('wymiana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plik', to='wymiana.Wymiana')),
            ],
        ),
    ]
