# Generated by Django 2.2.10 on 2020-04-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wymiana', '0004_auto_20200404_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WymianaFile',
            new_name='WymianaPlik',
        ),
    ]
