# Generated by Django 2.2.10 on 2020-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wymiana', '0005_auto_20200404_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wymianaplik',
            name='plik',
            field=models.FileField(upload_to='pliki'),
        ),
    ]
